# run: docker-compose up
version: "3"
services:
  webapp:
    container_name: course-authoring__webapp
    build:
      context: ./course-authoring/authoring-api/
      dockerfile: ./Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:3000"
    volumes:
      - ./course-authoring-storage:/course-authoring/storage
    restart: always
    depends_on:
      - mongodb
    extra_hosts: 
      # for docker v20.10+
      - "host.docker.internal:host-gateway"
      # for docker < v20.10
      - "host.docker.internal:${HOST_IP}"
  mongodb:
    container_name: course-authoring__mongodb
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./course-authoring-storage:/bitnami/mongodb
